Labs-EU4/flashcards-client

- .travis.yml
- package.json
Added Travis Configuration File
https://trello.com/c/pAtLlwXZ
> (chore):set up travis.yml file with rules

- config-overrides.js
- src/pages/Home.js
- src/pages/Home.module.less
- theme.js
Enabled less modules within config-override.js, added demo module for Home.js, created theme.js for custom variables.
https://trello.com/c/itnt8LP1/23-css-and-styling-setup
> (chore)styling setup

- package.json
- src/components/ForgotPassword/FormComponent.js
- src/components/ForgotPassword/FormComponentChangePassword.js
- src/pages/Register/Register.js
- src/pages/Register/Register.test.js
- src/pages/Register/__snapshots__/Register.test.js.snap
- src/state/IsLoggedIn/IsLoggedInActionCreators.js
- src/state/userData/userDataActionCreators.js
https://trello.com/c/4uzdSkIO/8-user-can-create-a-new-account
> (chore) (register form testing)

- src/components/ForgotPassword/FormComponent.js
- src/pages/ForgotPassword/ForgotPassword.test.js
> Chore testing password forgot component

- src/components/formStyleComponent/FormHeader.js
- src/pages/ConfirmSignUp/ConfirmSignUp.test.js
> Chore changing logo

- src/components/ForgotPassword/FormComponentChangePassword.js
- src/components/formStyleComponent/FormHeader.js
- src/pages/ConfirmSignUp/ConfirmSignUp.js
- src/pages/ConfirmSignUp/ConfirmSignUp.test.js
- src/pages/ForgotPassword/ForgotPassword.test.js
- src/pages/ForgotPassword/ResetPassword.test.js
- src/pages/Login/__snapshots__/Login.test.js.snap
- src/pages/Register/__snapshots__/Register.test.js.snap
Its more tests for ResetPassword and ConfirmPassword
No Trello Card
> more tests

- package.json
- src/components/ForgotPassword/FormComponentChangePassword.js
- src/pages/404.js
- src/pages/ForgotPassword/ForgotPassword.test.js
- src/pages/ForgotPassword/ResetPassword.test.js
> added more tests, coverage for my components up to about 80% now

- src/layout/Dashboard/Dashboard.js
- src/layout/Dashboard/Dashboard.module.css
https://trello.com/c/k1mBdNYA/35-user-can-view-their-dashboard
> added logo to the dashboard

- src/state/actions/decks.js
- src/state/reducers/decks.js
- src/state/types/index.js
> updated redux

- src/components/Home/Home.js
- src/components/Home/Home.test.js
- src/components/ListDeckInfo/DeckList.js
- src/components/RecentDecks/RecentDecks.js
- src/components/RecentDecks/RecentDecks.module.css
- src/layout/Dashboard/Dashboard.js
- src/layout/Dashboard/Dashboard.module.css
> recent-decks

- src/state/actions/auth.js
Token is no longer set to local storage on signup
https://trello.com/c/EfIsHPKy/62-signup-sets-token-to-localstorage-makes-email-verification-redundant
> (fix) (token issue on signup)

- src/pages/404.js
- src/pages/four0four.module.css
404 styling, also trying to fix some merge conflicts with create new deck component we had earlier 
> 404 styling

- src/components/DeckBoard/deckCard.module.css
- src/components/Home/Home.module.css
- src/pages/PlayMode/PlayMode.module.less
- src/state/reducers/decks.js
Fix for play mode and styles of "Home" page
> Bugfix play n styles

- src/components/CreateCard/Cards.js
- src/components/CreateCard/__snapshots__/Cards.test.js.snap
- src/components/Home/__snapshots__/Home.test.js.snap
- src/components/ListDeckInfo/DeckCard.js
- src/components/ListDeckInfo/DeckList.js
- src/pages/PersonalDecks/PersonalDecks.js
- src/pages/PublicDecks/PublicDecks.js
- src/pages/ViewDeckCards/DeckCards.js
- src/router/RoutesConfig.js
- src/state/actions/decks.js
- src/state/reducers/decks.js
Got rid of things like console logs and slightly restructured the Deck View files. Also edit/delete buttons for cards will now only display if a deck is clicked on from the Deck Library page.
> Chore cards cleanup

- src/components/CreateCard/Cards.js
- src/state/reducers/decks.js
- src/utils/diffArrays.js
Fixed an issues in the diffArray.js file where it was adding 1 to the tag.id number. This allows the decks to be updated without issue.
> Fix update my decks

- src/components/DeckBoard/DeckContainer.js
- src/components/DeckBoard/deckCard.module.css
Add deck limit and scrolling for deckcontainer on dashboard
> Chore add deckcontainer scrolling

- README.md
> Frontend-documentation

- src/components/CreateCard/__snapshots__/Cards.test.js.snap
- src/components/ListDeckInfo/__tests__/__snapshots__/HeaderSearchBar.test.js.snap
- src/components/NewDeckForm/NewDeckForm.js
- src/pages/PersonalDecks/__snapshots__/PersonalDecks.test.js.snap
- src/pages/PublicDecks/__snapshots__/PublicDecks.test.js.snap
- src/state/actions/decks.js
When a new deck is created the deck card is displayed with deck name instead of a blank card and on a successful create new deck post request the user will now be redirected to a single deck view page so they can add cards to the new deck.
> Fix create new deck issues

- src/components/CreateCard/AddCard.js
- src/components/CreateCard/UpdateCard.js
> disabling of add and update card buttons

- src/components/DeckBoard/DeckCard.js
- src/components/Home/__snapshots__/Home.test.js.snap
- src/components/PlayMode/ErrorHandlingScreen/ErrorHandlingScreen.js
- src/components/PlayMode/ErrorHandlingScreen/ErrorHandlingScreen.module.css
- src/components/RecentDecks/RecentDecks.js
- src/state/actions/decks.js
Changed header in RecentDecks.js from 'Recently played' to "Recent Decks". Added links to deckview from both containers on dashboard.
> Recent decks header and fixes

- src/components/CreateCard/AddCard.module.css
- src/components/CreateCard/Cards.js
no cards to display set to center
>  no cards to display set to center

- src/components/NewDeckForm/NewDeckForm.js
> New Deck Form
